name: Build & test image

on:
  workflow_call:
    inputs:
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      release:
        type: boolean
        default: true
    secrets:
      push-token:
        # See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
        description: To trigger the `publish` workflow use a GitHub App installation access token
                     or a personal access token
        required: true

jobs:
  build:
    name: Build & test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          persist-credentials: false    # Prevent credentials conflict when running `semantic-release`
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # v3.17
        with:
          detached: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Build and export locally to Docker
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          load: true
          tags: ${{ inputs.image-namespace }}/${{ inputs.image-repo }}:local-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install Test Kitchen
        uses: actionshub/chef-install@d41f8dde8642d5cd05abefa333fbf2784cff830c # 3.0.0
        env:
          # renovate: datasource=github-tags depName=chef/chef-workstation
          CHEF_WS_VERSION: 24.2.1058
        with:
          project: chef-workstation
          version: ${{ env.CHEF_WS_VERSION }}
      - name: Prepare Test Kitchen
        env:
          CHEF_LICENSE: accept-silent
          # renovate: datasource=rubygems depName=kitchen-docker
          KITCHEN-DOCKER_VERSION: 3.0.0
        run: chef gem install kitchen-docker --version ${{ env.KITCHEN-DOCKER_VERSION }}
      - name: Run Test Kitchen
        run: kitchen test
      - name: Run `semantic-release`
        uses: codfish/semantic-release-action@b0e57c976bf8f74b2454f59a30e4a1b5f11727b4 # v3.3.0
        id: sem-rel
        with:
          dry-run: ${{ !inputs.release }}
          plugins: |
            [ "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.push-token }}
