name: Build & Test

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
  push:
    branches:
      - '**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=actions/python-versions extractVersion=^(?<version>\S+)-\d+$
      PYTHON_VERSION: 3.12.3
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  run-test-workflow:
    name: Run `test` workflow
    needs:
      - pre-commit
    uses: ./.github/workflows/libtest.yml
    permissions:
      contents: write
    with:
      image-namespace: dafyddj
      image-repo: tmp-renovate
    secrets:
      push-token: ${{ secrets.PUSH_TOKEN }}
