name: Build & Test

on:
  pull_request:
  push:
    branches:
      - '**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  run-test-workflow:
    name: Run `test` workflow
    needs:
      - pre-commit
    uses: ./.github/workflows/libtest.yml
    permissions:
      contents: write
    with:
      image-namespace: techneg
      image-repo: ci-pre-commit
    secrets:
      push-token: ${{ secrets.PUSH_TOKEN }}
